-- 2026-09-18 · DATA ONLY, AND SAFE TO RUN TWICE.
--
-- WHAT HAPPENED. The first version of this file mixed the eight ALTER TABLE statements with this UPDATE and was
-- handed to `wrangler d1 execute --file`, which sends the whole file as ONE batch: the first statement that
-- errors aborts everything after it, and the CLI reports a rollback (D1 surfaces the torn-down session as
-- {"D1_RESET_DO":true}). The eight columns ARE on the remote database — the live CREATE text shows them
-- appended after submitted_at, in this file's order, which is the signature of ALTER TABLE ADD COLUMN and not
-- of a CREATE from schema.sql — so the DDL landed and a re-run then failed at its own first line with
-- `duplicate column name: seller_type`. SQLite has no ADD COLUMN IF NOT EXISTS, so a DDL file like that can
-- never be idempotent. The columns are therefore applied per-statement now, by migrations_merchant_columns.sh,
-- where one duplicate cannot abort the others; this file keeps only the data change.
--
-- IDEMPOTENT: the WHERE clause is the guard. Running it again touches nothing, because nothing is 'pending' any
-- more. The timestamp is a LITERAL, not datetime('now'), so the statement is a constant expression.
--
--   npx wrangler d1 execute vezvezak --remote --file=./migrations_merchant_fields.sql
--
-- The catalogue items already in the database were all 'pending', and until 2026-09-18 nothing could move them:
-- the only writer of 'live' was an AI branch that is off in production. They are published under the same rule
-- as a new item — listed by the merchant, unverified — except any the deterministic prohibited screen already
-- rejected, which stay rejected because this only touches 'pending'.
UPDATE catalog_items SET status = 'live', updated_at = '2026-09-18T00:00:00.000Z' WHERE status = 'pending';
